name: test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5433/template_test
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun run test
